### ISSUE TITLE
RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x2 and 6x64)

### ISSUE THREAD

**Issue by lhoangan** [VICO-UoE/MTPSL#3]
Hi, 
Thank you for your work. The code at `cityscapes_mtl_xtc.py` bounced with this error. Could you please have a look? I'm using torch 1.12.0 + cu116.

```
Traceback (most recent call last):
  File "/share/castor/home/leh/projects/MTPSL/cityscapes_mtl_xtc.py", line 191, in <module>
    con_loss = mapfns(train_pred_ind, train_target_ind, feat_aug[ind_].unsqueeze(0), copy.deepcopy(w), ssl_type=opt.ssl_type)
 File "/share/castor/home/leh/projects/MTPSL/model/mapfns.py", line 167, in forward
    mapout_source = self.mapfns(source_pred, input_task=source_task)
File "/share/castor/home/leh/projects/MTPSL/model/mapfns.py", line 90, in forward
    g_encoder[i][0] = self.encoder_block[i](x)
File "/share/castor/home/leh/projects/MTPSL/model/mapfns.py", line 36, in forward
    gamma = torch.mm(A_taskpair, self.gamma.t())
RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x2 and 6x64)
```

**Comment by WeihongLi-ac** [comment]
Hi,

I have pushed an update and the update should solve the problem. Thanks!

**Comment by lhoangan** [comment]
Perfect! Thank you for the promptly fix.
